const fs=require('fs');
const assert=require('assert');
const path=require('path');
const root=path.join(__dirname,'..');
const api=fs.readFileSync(path.join(root,'directory-api/src/index.js'),'utf8');
const legacy=fs.readFileSync(path.join(root,'server/index.mjs'),'utf8');
const app=fs.readFileSync(path.join(root,'src/App.tsx'),'utf8');
const chat=fs.readFileSync(path.join(root,'src/ChatView.tsx'),'utf8');
const sw=fs.readFileSync(path.join(root,'src/sw.js'),'utf8');
const customizationMigration=fs.readFileSync(path.join(root,'directory-api/migrations/0022_social_customization.sql'),'utf8');
assert.match(api,/access-control-allow-methods': 'GET, POST, PUT, DELETE, OPTIONS'/);
assert.doesNotMatch(api,/console\.error\(['"]INVALID_JSON_BODY/);
assert.match(api,/async function body\(request\) \{[\s\S]*?return JSON\.parse\(await request\.text\(\)\);[\s\S]*?catch/);
assert.match(legacy,/Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'/);
assert.match(api,/DEV_WTINK_ID = 'WTINKID-214994'/);
assert.match(api,/function roleFlags\(row\)/);
assert.match(api,/const isDev = id === DEV_WTINK_ID;/);
assert.match(api,/const isAdmin = id === DEV_WTINK_ID;/);
assert.match(api,/if \(!owner \|\| !roleFlags\(owner\)\.isAdmin\) return null;/);
assert.match(api,/chat\/keys/);
assert.match(api,/CHAT_KEY_ROTATION_BLOCKED/);
assert.match(api,/path==='\/chat\/keys\/me'/);
assert.match(api,/const isSelf=target===normalizeId\(owner\.wtink_id\)/);
assert.match(app,/authProfileReady/);
assert.match(app,/getOwnChatKey/);
assert.match(app,/getChatIdentityMatching/);
assert.doesNotMatch(api,/auth\/qr\//);
assert.doesNotMatch(app,/Вход на ПК по QR|QrLoginPanel|startQrLogin/);
assert.match(api,/auth_sessions/);
assert.match(api,/social_messages \(id,sender_id,receiver_id,body,kind,mime,name,created_at\)/);
assert.match(api,/webauthn_credentials\(id,profile_id,user_id,public_key,counter,device_type,backed_up,transports,device_name,created_at,updated_at\).*VALUES \(\?1,\?2,\?3,\?4,\?5,\?6,\?7,\?8,\?9,\?10,\?11\)/);
assert.match(api,/!\['voice','image','video','file'\]\.includes\(kind\)/);
assert.match(api,/body:r\.body,kind:r\.kind/);
assert.doesNotMatch(app,/Входящий P2P-запрос/);
assert.doesNotMatch(app,/workertink:peer-action/);
assert.match(chat,/E2E/);
assert.match(chat,/sendChatMessage/);
assert.match(chat,/chat-file-input/);
assert.match(chat,/Применить заметку/);
assert.match(sw,/precacheAndRoute/);
console.log('WorkerTink API regression tests: OK');

assert.match(customizationMigration,/ALTER TABLE profiles ADD COLUMN banner/);
assert.match(customizationMigration,/ALTER TABLE social_posts ADD COLUMN attachments/);
assert.match(customizationMigration,/ALTER TABLE social_posts ADD COLUMN shift_note/);
assert.match(api,/UPDATE social_groups SET name=\?1,description=\?2,visibility=\?3,icon=\?4,accent=\?5,cover=\?6,rules=\?7/);
assert.match(api,/UPDATE company_channels SET name=\?1,company_name=\?2,description=\?3,visibility=\?4,icon=\?5,accent=\?6,cover=\?7,topic=\?8/);
assert.match(api,/function cleanShiftNote/);

const verificationMigration=fs.readFileSync(path.join(root,'directory-api/migrations/0023_profile_verification.sql'),'utf8');
assert.match(verificationMigration,/is_official/);
assert.match(verificationMigration,/is_verified/);
assert.match(verificationMigration,/privacy_policy_version/);
assert.match(verificationMigration,/terms_version/);
assert.match(verificationMigration,/verification_requests/);
assert.match(api,/verification\/request/);
assert.match(api,/admin\/verification/);
assert.match(api,/admin\/profiles\/\(\[\^\/\]\+\)\/official/);
assert.match(api,/is_verified = 1/);
assert.match(api,/is_verified=0/);
assert.match(api,/RULES_ACCEPTANCE_REQUIRED/);
assert.match(app,/Политику конфиденциальности/);
assert.match(app,/Условия использования/);
assert.match(app,/Заявка на верификацию/);
assert.match(app,/ProfileQrModal/);
assert.match(app,/Admin Control Center/);
console.log('WorkerTink verification/profile release tests: OK');
