const fs=require('fs');
const assert=require('assert');
const path=require('path');
const root=path.join(__dirname,'..');
const api=fs.readFileSync(path.join(root,'directory-api/src/index.js'),'utf8');
const legacy=fs.readFileSync(path.join(root,'server/index.mjs'),'utf8');
const app=fs.readFileSync(path.join(root,'src/App.tsx'),'utf8');
const chat=fs.readFileSync(path.join(root,'src/ChatView.tsx'),'utf8');
const sw=fs.readFileSync(path.join(root,'src/sw.js'),'utf8');
assert.match(api,/access-control-allow-methods': 'GET, POST, PUT, DELETE, OPTIONS'/);
assert.doesNotMatch(api,/console\.error\(['"]INVALID_JSON_BODY/);
assert.match(api,/async function body\(request\) \{[\s\S]*?return JSON\.parse\(await request\.text\(\)\);[\s\S]*?catch/);
assert.match(legacy,/Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'/);
assert.match(api,/DEV_WTINK_ID = 'WTINKID-214994'/);
assert.match(api,/function roleFlags\(row\)/);
assert.match(api,/const isDev = id === DEV_WTINK_ID;/);
assert.match(api,/const isAdmin = id === DEV_WTINK_ID;/);
assert.match(api,/if \(!owner \|\| !roleFlags\(owner\)\.isAdmin\) return null;/);
assert.match(api,/chat\/keys/);
assert.match(api,/auth\/qr\/start/);
assert.match(api,/auth\/qr\/approve/);
assert.match(api,/auth_sessions/);
assert.match(api,/social_messages \(id,sender_id,receiver_id,body,kind,mime,name,created_at\)/);
assert.match(api,/body:r\.body,kind:r\.kind/);
assert.match(app,/Вход на ПК по QR/);
assert.doesNotMatch(app,/Входящий P2P-запрос/);
assert.doesNotMatch(app,/workertink:peer-action/);
assert.match(chat,/E2E/);
assert.match(chat,/sendChatMessage/);
assert.match(sw,/precacheAndRoute/);
console.log('WorkerTink API regression tests: OK');
