const fs=require('fs'),assert=require('assert'),path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'src/App.tsx'),'utf8');
const core=fs.readFileSync(path.join(root,'src/core.ts'),'utf8');
const storage=fs.readFileSync(path.join(root,'src/storage.ts'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.match(app,/setupComplete/);
assert.match(app,/Аванс по умолчанию — 50% оклада/);
assert.match(app,/shiftNotes/);
assert.match(app,/shiftOverrides/);
assert.match(app,/Экспорт заметок \.md/);
assert.match(app,/Импорт заметок \.md/);
assert.match(app,/markdownToHtml/);
assert.match(app,/insertTable/);
assert.match(app,/markdown-wysiwyg/);
assert.match(app,/htmlToMarkdown/);
assert.match(app,/contentEditable/);
assert.match(core,/export function getShift/);
assert.match(core,/export function getScheduledShift/);
assert.match(storage,/workertink:v3/);
assert.match(index,/viewport-fit=cover/);
assert.ok(fs.existsSync(path.join(root,'LICENSE')));
console.log('WorkerTink smoke tests: OK');
