const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const api=fs.readFileSync(path.join(root,'directory-api/src/index.js'),'utf8');
const dir=fs.readFileSync(path.join(root,'src/directory.ts'),'utf8');
const app=fs.readFileSync(path.join(root,'src/App.tsx'),'utf8');
const social=fs.readFileSync(path.join(root,'src/SocialView.tsx'),'utf8');
const chat=fs.readFileSync(path.join(root,'src/ChatView.tsx'),'utf8');
const home=fs.readFileSync(path.join(root,'src/HomeView.tsx'),'utf8');
const migration=fs.readFileSync(path.join(root,'directory-api/migrations/0010_social_network.sql'),'utf8');
const chatMigration=fs.readFileSync(path.join(root,'directory-api/migrations/0012_chat_e2ee_qr.sql'),'utf8');
for(const x of ['/social/feed','/social/posts','/social/notifications','/social/messages','/chat/messages','/chat/keys']) if(!api.includes(x)) throw new Error(`missing API route ${x}`);
for(const x of ['social_posts','social_post_likes','social_post_comments','social_notifications','social_messages']) if(!migration.includes(x)) throw new Error(`missing table ${x}`);
for(const x of ['chat_device_keys','auth_sessions']) if(!chatMigration.includes(x)) throw new Error(`missing table ${x}`);
const pins=fs.readFileSync(path.join(root,'directory-api/migrations/0021_chat_pins.sql'),'utf8');
for(const x of ['chat_message_pins','idx_chat_message_pins_profile']) if(!pins.includes(x)) throw new Error(`missing chat pin schema ${x}`);
if(!api.includes('chatPinListMatch')||!api.includes('chatPinMatch')) throw new Error('missing chat pin API');
if(!dir.includes('getChatPins')||!dir.includes('pinChatMessage')||!dir.includes('unpinChatMessage')) throw new Error('missing chat pin client API');
for(const x of ['getSocialFeed','createSocialPost','toggleSocialLike','addSocialComment','getSocialNotifications','getChatMessages','sendChatMessage','putChatKey']) if(!dir.includes(x)) throw new Error(`missing client API ${x}`);
for(const x of ['Лента','Уведомления','Люди']) if(!social.includes(x)) throw new Error(`missing social section ${x}`);
if(social.includes("section==='messages'")) throw new Error('community chat section must be removed');
for(const x of ['E2E','Фото','Видео','Голос','Остановить и отправить']) if(!chat.includes(x)) throw new Error(`missing protected chat feature ${x}`);
for(const x of ['Salary Forecast','Vacation Planner','Sick Simulator','What If?','Encrypted Backup']) if(!home.includes(x)) throw new Error(`missing enhancement ${x}`);
console.log('WorkerTink social/protected-chat regression tests: OK');

if(/\/auth\/qr\//.test(api)) throw new Error('QR auth routes must be removed');
if(/startQrLogin|pollQrLogin|approveQrLogin|QrLoginPanel/.test(app)) throw new Error('QR auth client code must be removed');
