import assert from 'node:assert/strict';
import {DEFAULT} from '../src/core.ts';
import {normalizeState} from '../src/storage.ts';

const legacy={...DEFAULT,setupComplete:true,schemaVersion:3,scheduleType:'5/2',scheduleShift:'full',nightExtraPercent:undefined};
const normalized=normalizeState(legacy);
assert.equal(normalized.schemaVersion,8);
assert.equal(normalized.scheduleShift,'day');
assert.equal(normalized.nightExtraPercent,20);
assert.equal(normalized.scheduleType,'5/2');
assert.equal(normalized.setupComplete,true);
assert.equal(normalized.profile.name,'');
assert.deepEqual(normalized.friends,{});
assert.deepEqual(normalized.friendRequestsIncoming,[]);
assert.deepEqual(normalized.friendRequestsOutgoing,[]);
assert.match(normalized.profile.profileId,/^WTinkID-\d{6}$/);
assert.deepEqual(normalized.chats,{});
assert.equal(normalized.notifications.enabled,true);
assert.equal(normalized.notifications.messages,true);
assert.equal(normalized.onePassEnabled,false);
console.log('WorkerTink storage migration tests: OK');
