const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'src/App.tsx'),'utf8');
const network=fs.readFileSync(path.join(root,'src/NetworkView.tsx'),'utf8');
const channels=fs.readFileSync(path.join(root,'src/ChannelsView.tsx'),'utf8');
const spaceControls=fs.readFileSync(path.join(root,'src/SpaceControls.tsx'),'utf8');
const ui=fs.readFileSync(path.join(root,'src/ui.css'),'utf8');
const update=fs.readFileSync(path.join(root,'src/UpdateGate.tsx'),'utf8');
const pull=fs.readFileSync(path.join(root,'src/PullToRefresh.tsx'),'utf8');
const shell=fs.readFileSync(path.join(root,'src/AppShell.tsx'),'utf8');
if(fs.existsSync(path.join(root,'src/V7Shell.tsx'))) throw new Error('legacy V7 shell file still exists');
const sw=fs.readFileSync(path.join(root,'src/sw.js'),'utf8');
const workflow=fs.readFileSync(path.join(root,'.github/workflows/deploy.yml'),'utf8');
const packageJson=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));

const home=fs.readFileSync(path.join(root,'src/HomeView.tsx'),'utf8');
const notifications=fs.readFileSync(path.join(root,'src/NotificationsView.tsx'),'utf8');
const chats=fs.readFileSync(path.join(root,'src/ChatsHub.tsx'),'utf8');
const chat=fs.readFileSync(path.join(root,'src/ChatView.tsx'),'utf8');
const groupChat=fs.readFileSync(path.join(root,'src/GroupChatView.tsx'),'utf8');
if(shell.includes('v7-shell')||!shell.includes('wt-shell')||!shell.includes('wt-mobile-nav')) throw new Error('legacy shell was not replaced');
if(!ui.includes('.wt-shell')||!ui.includes('.wt-nav-item.active')||!ui.includes('.wt-command-search')) throw new Error('new workspace design system missing');
if(!ui.includes('.social-hero')||!ui.includes('.work-kpis')||!ui.includes('.notification-timeline')) throw new Error('new page design system missing');
for(const legacy of ['styles.css','design.css','v7.css','rebuild.css']) if(fs.existsSync(path.join(root,'src',legacy))) throw new Error(`legacy stylesheet remains: ${legacy}`);
if(!app.includes('BannerEditorModal')) throw new Error('profile banner editor missing');
if(!app.includes('Скопировать ссылку')) throw new Error('profile link copy action missing');
if(!network.includes('Обложка')) throw new Error('community customization UI missing');
if(!channels.includes('Оформить канал')) throw new Error('channel customization UI missing');
if(!spaceControls.includes('SpaceIconPicker')||!spaceControls.includes('SpaceThemePicker')) throw new Error('space picker controls missing');
if(!channels.includes('canManage')||!channels.includes('deleteCompanyChannel')) throw new Error('channel owner guard missing');
if(!network.includes('SpaceIconPicker')||!network.includes('SpaceThemePicker')||!network.includes('Удалить сообщество')) throw new Error('community owner customization controls missing');
if(!ui.includes('.profile-cover{')||!ui.includes('background-size:cover')) throw new Error('profile banner rendering CSS fix missing');
if(!app.includes('deleteNetworkGroup')||!app.includes('deleteCompanyChannel')) throw new Error('admin space moderation actions missing');
if(!network.includes('post-attachment-v2')) throw new Error('flexible post attachment rendering missing');
const work=fs.readFileSync(path.join(root,'src/WorkHubView.tsx'),'utf8');
const rebuildCss=ui;

for(const x of ['redesign-home','Ваш график','Сценарий выплаты','Резервная копия']) if(!home.includes(x)) throw new Error('rebuilt home surface missing '+x);
for(const x of ['redesign-notifications','notification-timeline','timeline-item']) if(!notifications.includes(x)) throw new Error('rebuilt notification surface missing '+x);
for(const x of ['redesign-chats','chats-mode-nav','Формат разговора']) if(!chats.includes(x)) throw new Error('rebuilt chats surface missing '+x);
if(!chat.includes('chat-page-rebuilt')) throw new Error('rebuilt personal chat surface missing');
if(!groupChat.includes('URL.revokeObjectURL')||!groupChat.includes('mediaUrlsRef')) throw new Error('group chat media object URL cleanup missing');
if(!chat.includes('is-empty')) throw new Error('chat empty-state contract missing');
if(!work.includes('redesign-work')) throw new Error('rebuilt work surface missing');
if(!rebuildCss.includes('.v7-work-page.calendar-layout>.v7-page-header')) throw new Error('calendar header grid fix missing');
if(!rebuildCss.includes('.redesign-chats .chats-mode-nav button')) throw new Error('chat mode tab styling missing');
if(!rebuildCss.includes('.v7-work-page.calendar-layout{display:grid!important')||!rebuildCss.includes("grid-template-areas:'header' 'calendar' 'summary'")) throw new Error('calendar full-width grid contract missing');
if(!network.includes('PostAttachment')||!network.includes('shift-note-editor')||!network.includes('post-attachments-v2')||!network.includes('groupAttachments')) throw new Error('rich post surface missing');
if(!app.includes('Добавить баннер')||!app.includes('profile.username')||!app.includes('searchUser(profile.profileId)')||!app.includes('const cached=id===normalizeWTinkId(state.profile.profileId)')) throw new Error('profile customization or username hydration missing');
for(const x of ['.redesign-page-intro','.home-snapshot','.network-layout-v2','.notification-timeline','.chat-page-rebuilt','.redesign-work']) if(!rebuildCss.includes(x)) throw new Error('rebuilt design token missing '+x);

if(!app.includes('syncTabUrl=(next:Tab)=>')) throw new Error('navigation URL sync is missing');
if(!app.includes("const openChat=(profileId:string)=>{syncTabUrl('chat')")) throw new Error('chat navigation does not use the canonical URL sync');
if(!app.includes("window.history.replaceState({},'',url.pathname+url.search+url.hash)")) throw new Error('navigation URL sync does not write browser URL');
if(app.includes('<main className={')) throw new Error('nested main remains inside V7Shell');
if(!app.includes('</div>\n</V7Shell>')) throw new Error('v7 page container is not closed as a div');
if(!app.includes("message.includes('UNAUTHORIZED')||message.includes('HTTP_401')")) throw new Error('expired-session recovery is missing');
if(!app.includes("directoryToken:'',onePassEnabled:false")) throw new Error('expired-session recovery does not clear credentials');

if(!network.includes('Promise.allSettled([getNetworkHome(token)')) throw new Error('network refresh failure isolation is missing');
if(!network.includes("if(savedResult.status==='fulfilled')setSaved(savedResult.value.posts);else setSaved([])")) throw new Error('saved posts must be optional during network refresh');
if(network.includes('Promise.all([getNetworkHome(token),import(\'./directory\').then(m=>m.getSocialFeed(token,60)),getSavedNetworkPosts(token)])')) throw new Error('network refresh still fails atomically on saved posts');

if(!update.includes("updateSWRef.current(true)")) throw new Error('PWA update must activate the waiting worker and reload');
if(update.includes("updateSWRef.current(false)")) throw new Error('PWA update must not leave the worker waiting after confirmation');
if(!update.includes("localStorage.removeItem(BUILD_STORAGE_KEY)")) throw new Error('failed update must reset build marker');
if(!sw.includes("event.data?.type==='SKIP_WAITING'")||!sw.includes('self.skipWaiting()')) throw new Error('custom prompt service worker missing SKIP_WAITING handler');
if(!update.includes('WTINKER')) throw new Error('UpdateGate brand was not migrated');
if(!pull.includes('EDGE_START')||!pull.includes('TRIGGER_DISTANCE')) throw new Error('PWA pull-to-refresh thresholds missing');
if(!pull.includes("display-mode: standalone")) throw new Error('pull-to-refresh must be PWA-only');
if(!pull.includes("event.preventDefault()")) throw new Error('pull-to-refresh must suppress native overscroll while pulling');
if(!pull.includes("window.location.reload()")) throw new Error('pull-to-refresh reload action missing');
if(!pull.includes('pull-refresh-indicator')||!pull.includes("setPhase('refreshing')")) throw new Error('pull-to-refresh animated indicator missing');


if(!sw.includes("title:'WTinker'")) throw new Error('service worker default notification brand is stale');
if(packageJson.scripts?.api!=='npm run directory:dev') throw new Error('root api script must use the production-equivalent Directory API');
if(fs.existsSync(path.join(root,'directory-api/.wrangler'))) throw new Error('tracked local Wrangler state must not be present in repository');
if(fs.existsSync(path.join(root,'tsconfig.tsbuildinfo'))) throw new Error('generated TypeScript build info must not be tracked');
if(!workflow.includes('VITE_BUILD_ID: ${{ github.sha }}')) throw new Error('production build ID is not injected');
console.log('WTinker system integrity regression tests: OK');