import {useState} from 'react';
import type {UserProfile,State} from './core';
import ChatView from './ChatView';
import GroupChatView from './GroupChatView';
import ChannelsView from './ChannelsView';
export default function ChatsHub({token,profile,state,onStateChange,onNotice,onProfile,routePath}:{token:string;profile:UserProfile;state:State;onStateChange:(p:Partial<State>)=>void;onNotice:(s:string)=>void;onProfile?:(profile:UserProfile)=>void;routePath?:string}){
 const [mode,setMode]=useState<'personal'|'groups'|'channels'>(()=>routePath?.startsWith('/chat/group/')?'groups':routePath?.startsWith('/channel/')?'channels':'personal');
 const groupId=routePath?.match(/^\/chat\/group\/([^/]+)/)?.[1]; const channelSlug=routePath?.match(/^\/channel\/([^/]+)/)?.[1];
 return <section className="canva-page canva-chats redesign-page redesign-chats chats-hub"><header className="canva-page-head"><div><span className="redesign-overline">Общение</span><h1>Разговоры, которые не теряются</h1><p>Личные E2E-чаты, групповые обсуждения и корпоративные каналы — разные форматы одного общения.</p></div></header><div className="canva-chat-switch chats-mode-nav"><div className="chats-mode-copy"><b>Формат разговора</b><span>Выберите пространство</span></div><button type="button" aria-pressed={mode==='personal'} className={mode==='personal'?'active':''} onClick={()=>setMode('personal')}><span>Личные</span><small>E2E</small></button><button type="button" aria-pressed={mode==='groups'} className={mode==='groups'?'active':''} onClick={()=>setMode('groups')}><span>Группы</span><small>команды</small></button><button type="button" aria-pressed={mode==='channels'} className={mode==='channels'?'active':''} onClick={()=>setMode('channels')}><span>Каналы</span><small>корпоративные</small></button></div>{mode==='personal'&&<ChatView token={token} profile={profile} state={state} onStateChange={onStateChange} onNotice={onNotice} onProfile={onProfile}/>} {mode==='groups'&&<GroupChatView token={token} profile={profile} onNotice={onNotice} onProfile={onProfile} initialGroupId={groupId}/>} {mode==='channels'&&<ChannelsView token={token} profile={profile} onNotice={onNotice} onProfile={onProfile} initialSlug={channelSlug}/>}</section>
}
