import {useMemo,useState} from 'react';
import {calcMonth,calcYear,formatMoney,getScheduledShift,parseYmd,addDays,ymd,vacationCalendarDays,type State} from './core';

type Props={state:State;patch:(p:Partial<State>)=>void;onNotice:(s:string)=>void;go:(tab:'social'|'calendar'|'pay'|'absence'|'profile'|'settings')=>void};
const iso=(d:Date)=>ymd(d);
function download(name:string,blob:Blob){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function encryptBackup(state:State,password:string){const enc=new TextEncoder();const salt=crypto.getRandomValues(new Uint8Array(16));const iv=crypto.getRandomValues(new Uint8Array(12));const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']);const data=enc.encode(JSON.stringify(state));const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data));const out=new Uint8Array(4+salt.length+iv.length+cipher.length);out.set([87,84,66,49]);out.set(salt,4);out.set(iv,20);out.set(cipher,32);return new Blob([out],{type:'application/octet-stream'})}
function daysOff(state:State,days:number){let off=0;const start=new Date();for(let i=0;i<days;i++){const d=addDays(start,i);if(getScheduledShift(state,d)==='off')off++}return off}
export default function HomeView({state,patch,onNotice,go}:Props){
 const now=new Date(), month=calcMonth(state,now.getFullYear(),now.getMonth()), year=useMemo(()=>calcYear(state,now.getFullYear()),[state,now.getFullYear()]);
 const [forecastMonths,setForecastMonths]=useState(3); const [scenarioSalary,setScenarioSalary]=useState(state.salary); const [scenarioNight,setScenarioNight]=useState(state.nightExtraPercent); const [vacStart,setVacStart]=useState(''); const [vacLength,setVacLength]=useState(14); const [sickDays,setSickDays]=useState(5); const [tip,setTip]=useState(''); const [backupPassword,setBackupPassword]=useState('');
 const forecast=useMemo(()=>{let gross=0,net=0;for(let i=0;i<forecastMonths;i++){const d=new Date(now.getFullYear(),now.getMonth()+i,1);const c=calcMonth(state,d.getFullYear(),d.getMonth());gross+=c.gross;net+=c.net}return {gross,net,avg:net/forecastMonths}},[state,forecastMonths]);
 const scenario=useMemo(()=>{const copy={...state,salary:Math.max(0,scenarioSalary),nightExtraPercent:Math.max(0,scenarioNight)} as State;const c=calcMonth(copy,now.getFullYear(),now.getMonth());return c},[state,scenarioSalary,scenarioNight]);
 const plannedVacation=useMemo(()=>{if(!vacStart)return null;const start=parseYmd(vacStart);const end=addDays(start,Math.max(0,vacLength-1));const period={start:iso(start),end:iso(end)};return {period,days:vacationCalendarDays(state,period),balance:Math.max(0,state.vacTotal-vacationCalendarDays(state,period))}},[state,vacStart,vacLength]);
 const sickRate=state.stage<5?.6:state.stage<8?.8:1;const sickPay=Math.round((state.salary/730)*sickRate*sickDays);
 const tips=useMemo(()=>{const list:string[]=[];if(month.sickDays)list.push('В этом месяце есть больничные — проверьте средний заработок и даты выплат.');if(month.vacDays)list.push('В текущем месяце есть отпуск — проверьте остаток дней.');if(month.nightWork)list.push('Есть ночные смены — убедитесь, что процент ночной доплаты актуален.');if(year.averageMonthlyNet&&year.averageMonthlyNet<state.salary*(1-state.taxRate/100)*.8)list.push('Средний доход ниже обычного оклада — проверьте ручные выходы и отсутствия.');return list.length?list:['График и выплаты синхронизированы. Можно перейти в Сообщество и поделиться рабочей новостью.']},[month,year,state]);
 const saveTip=()=>{if(!tip.trim())return;patch({shiftNotes:{...state.shiftNotes,[iso(now)]:`${state.shiftNotes[iso(now)]||''}${state.shiftNotes[iso(now)]?'\n':''}${tip.trim()}`}});setTip('');onNotice('Совет сохранён в заметках текущего дня')};
 const backup=async()=>{if(!backupPassword){onNotice('Введите пароль для шифрования резервной копии');return}try{download(`workertink-backup-${iso(now)}.wtbackup`,await encryptBackup(state,backupPassword));setBackupPassword('');onNotice('Зашифрованная резервная копия создана')}catch{onNotice('Не удалось создать резервную копию')}};
 return <section className="home-page">
  <div className="dashboard-hero"><div><span className="eyebrow">Сегодня · {now.toLocaleDateString('ru-RU')}</span><h2>Ваш WorkerTink</h2><p>График, деньги, отсутствия и рабочее сообщество — на одном экране.</p></div><div className="dashboard-actions"><button className="btn primary" onClick={()=>go('social')}>Открыть сообщество</button><button className="btn quiet" onClick={()=>go('calendar')}>Календарь</button></div></div>
  <div className="dashboard-kpis"><div><span>На руки сейчас</span><b>{formatMoney(month.net)}</b><small>{month.work} смен · {month.sickDays} больничных дней</small></div><div><span>Годовой доход</span><b>{formatMoney(year.net)}</b><small>среднее {formatMoney(year.averageMonthlyNet)}/мес.</small></div><div><span>Отпуск</span><b>{Math.max(0,state.vacTotal-state.vacations.reduce((n,p)=>n+vacationCalendarDays(state,p),0))}</b><small>дней осталось</small></div><div><span>Контроль</span><b>{daysOff(state,30)}</b><small>выходных в ближайшие 30 дней</small></div></div>
  <div className="enhance-grid">
   <article className="enhance-card"><span className="eyebrow">1 · Smart Dashboard</span><h3>Следующие 7 дней</h3><div className="mini-timeline">{Array.from({length:7},(_,i)=>{const d=addDays(now,i);const s=getScheduledShift(state,d);return <div key={i}><b>{d.getDate()}</b><span>{d.toLocaleDateString('ru-RU',{weekday:'short'})}</span><em>{s==='off'?'ВЫХ':s==='night'?'Ночь':s==='full'?'Сутки':'День'}</em></div>})}</div></article>
   <article className="enhance-card"><span className="eyebrow">2 · Smart Calendar</span><h3>Быстрый контроль</h3><p>Автоматически учитываются график, ручные изменения, праздники, отпуск и больничный.</p><button className="btn quiet" onClick={()=>go('calendar')}>Открыть умный календарь →</button></article>
   <article className="enhance-card"><span className="eyebrow">3 · Salary Forecast</span><h3>Прогноз на {forecastMonths} мес.</h3><div className="forecast-value">{formatMoney(forecast.net)}</div><input type="range" min="1" max="12" value={forecastMonths} onChange={e=>setForecastMonths(Number(e.target.value))}/><small>Среднее: {formatMoney(forecast.avg)} в месяц</small></article>
   <article className="enhance-card"><span className="eyebrow">4 · Vacation Planner</span><h3>План отпуска</h3><div className="compact-row"><input type="date" value={vacStart} onChange={e=>setVacStart(e.target.value)}/><input type="number" min="1" max="60" value={vacLength} onChange={e=>setVacLength(Number(e.target.value)||1)}/></div>{plannedVacation?<p>{plannedVacation.period.start} → {plannedVacation.period.end}<br/><b>{plannedVacation.days} оплачиваемых дней</b></p>:<p>Выберите начало и длительность.</p>}</article>
   <article className="enhance-card"><span className="eyebrow">5 · Sick Simulator</span><h3>Больничный</h3><input type="range" min="1" max="30" value={sickDays} onChange={e=>setSickDays(Number(e.target.value))}/><p>{sickDays} дней × {Math.round(sickRate*100)}% ≈ <b>{formatMoney(sickPay)}</b></p><small>Расчёт по текущему среднему доходу и стажу.</small></article>
   <article className="enhance-card enhance-social"><span className="eyebrow">6 · WorkerTink Social</span><h3>Рабочее сообщество</h3><p>Лента публикаций, реакции, комментарии, личные сообщения, заявки и профили коллег в едином контуре.</p><button className="btn primary" onClick={()=>go('social')}>Перейти в сообщество →</button></article>
   <article className="enhance-card"><span className="eyebrow">7 · Presence</span><h3>Кто на связи</h3><p>Статус присутствия обновляется автоматически через heartbeat. В разделе «Сообщество» отображается онлайн-статус друзей.</p><button className="btn quiet" onClick={()=>go('social')}>Посмотреть людей →</button></article>
   <article className="enhance-card"><span className="eyebrow">8 · Security Center</span><h3>Защита аккаунта</h3><p>PIN хранится как PBKDF2-хэш, OnePass/Passkey и серверная сессия доступны в настройках.</p><button className="btn quiet" onClick={()=>go('settings')}>Открыть безопасность →</button></article>
   <article className="enhance-card"><span className="eyebrow">9 · PWA / Offline</span><h3>Работает без сети</h3><p>Календарь и рабочие данные остаются локально. Социальные действия автоматически становятся доступны после восстановления соединения.</p></article>
   <article className="enhance-card"><span className="eyebrow">10 · Notification Center</span><h3>Все события в одном месте</h3><p>Заявки, реакции, комментарии и сообщения попадают во внутренний центр уведомлений и могут дублироваться push.</p><button className="btn quiet" onClick={()=>go('social')}>Открыть уведомления →</button></article>
   <article className="enhance-card"><span className="eyebrow">11 · Year Statistics</span><h3>Статистика года</h3><div className="stats-lines"><span>Смены <b>{year.work}</b></span><span>На руки <b>{formatMoney(year.net)}</b></span><span>Отпуск <b>{year.vacDays} дн.</b></span><span>Больничный <b>{year.sickDays} дн.</b></span></div><button className="btn quiet" onClick={()=>go('pay')}>Полная статистика →</button></article>
   <article className="enhance-card"><span className="eyebrow">12 · What If?</span><h3>Сценарий месяца</h3><label>Оклад <input type="number" value={scenarioSalary} onChange={e=>setScenarioSalary(Number(e.target.value)||0)}/></label><label>Ночная доплата {scenarioNight}% <input type="range" min="0" max="100" value={scenarioNight} onChange={e=>setScenarioNight(Number(e.target.value))}/></label><p>Сценарий «на руки»: <b>{formatMoney(scenario.net)}</b></p></article>
   <article className="enhance-card"><span className="eyebrow">13 · Admin</span><h3>Управление сетью</h3><p>Администратор видит профили, присутствие, заявки и может управлять сессиями. Dev-роль авторизуется сервером.</p>{state.profile.isAdmin&&<button className="btn quiet" onClick={()=>go('settings')}>Админка →</button>}</article>
   <article className="enhance-card"><span className="eyebrow">14 · Context Tips</span><h3>Совет дня</h3><p>{tips[0]}</p><div className="compact-row"><input value={tip} onChange={e=>setTip(e.target.value)} placeholder="Добавить свой совет…"/><button className="btn quiet" onClick={saveTip}>Сохранить</button></div></article>
   <article className="enhance-card"><span className="eyebrow">15 · Encrypted Backup</span><h3>Резервная копия</h3><p>Локальный экспорт шифруется AES-GCM, ключ выводится из вашего пароля через PBKDF2. Пароль не отправляется на сервер.</p><div className="compact-row"><input type="password" value={backupPassword} onChange={e=>setBackupPassword(e.target.value)} placeholder="Пароль резервной копии"/><button className="btn primary" onClick={()=>void backup()}>Экспорт</button></div></article>
  </div>
 </section>
}
