import {useMemo,useState} from 'react';
import {calcMonth,calcYear,formatMoney,getScheduledShift,parseYmd,addDays,ymd,vacationCalendarDays,vacationUsedDays,vacationProjectedUsedDays,sickPayForDays,type State} from './core';

type Props={state:State;patch:(p:Partial<State>)=>void;onNotice:(s:string)=>void;go:(tab:'social'|'calendar'|'pay'|'absence'|'profile'|'settings')=>void};
const iso=(d:Date)=>ymd(d);
function download(name:string,blob:Blob){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function encryptBackup(state:State,password:string){const enc=new TextEncoder();const salt=crypto.getRandomValues(new Uint8Array(16));const iv=crypto.getRandomValues(new Uint8Array(12));const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']);const data=enc.encode(JSON.stringify(state));const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data));const out=new Uint8Array(4+salt.length+iv.length+cipher.length);out.set([87,84,66,49]);out.set(salt,4);out.set(iv,20);out.set(cipher,32);return new Blob([out],{type:'application/octet-stream'})}
function daysOff(state:State,days:number){let off=0;const start=new Date();for(let i=0;i<days;i++){const d=addDays(start,i);if(getScheduledShift(state,d)==='off')off++}return off}
export default function HomeView({state,patch,onNotice,go}:Props){
 const now=new Date(), month=calcMonth(state,now.getFullYear(),now.getMonth()), year=useMemo(()=>calcYear(state,now.getFullYear()),[state,now.getFullYear()]);
 const [forecastMonths,setForecastMonths]=useState(3); const [scenarioSalary,setScenarioSalary]=useState(state.salary); const [scenarioNight,setScenarioNight]=useState(state.nightExtraPercent); const [vacStart,setVacStart]=useState(''); const [vacLength,setVacLength]=useState(14); const [sickDays,setSickDays]=useState(5); const [tip,setTip]=useState(''); const [backupPassword,setBackupPassword]=useState('');
 const forecast=useMemo(()=>{let gross=0,net=0;for(let i=0;i<forecastMonths;i++){const d=new Date(now.getFullYear(),now.getMonth()+i,1);const c=calcMonth(state,d.getFullYear(),d.getMonth());gross+=c.gross;net+=c.net}return {gross,net,avg:net/forecastMonths}},[state,forecastMonths]);
 const scenario=useMemo(()=>{const copy={...state,salary:Math.max(0,scenarioSalary),nightExtraPercent:Math.max(0,scenarioNight)} as State;const c=calcMonth(copy,now.getFullYear(),now.getMonth());return c},[state,scenarioSalary,scenarioNight]);
 const plannedVacation=useMemo(()=>{if(!vacStart)return null;const start=parseYmd(vacStart);const end=addDays(start,Math.max(0,vacLength-1));const period={start:iso(start),end:iso(end)};return {period,days:vacationCalendarDays(state,period),balance:Math.max(0,state.vacTotal-vacationProjectedUsedDays(state,period))}},[state,vacStart,vacLength]);
 const sickRate=state.stage<5?.6:state.stage<8?.8:1;const sickPay=sickPayForDays(state,now.getFullYear(),now.getMonth(),sickDays);
 const tips=useMemo(()=>{const list:string[]=[];if(month.sickDays)list.push('В этом месяце есть больничные — проверьте средний заработок и даты выплат.');if(month.vacDays)list.push('В текущем месяце есть отпуск — проверьте остаток дней.');if(month.nightWork)list.push('Есть ночные смены — убедитесь, что процент ночной доплаты актуален.');if(year.averageMonthlyNet&&year.averageMonthlyNet<state.salary*(1-state.taxRate/100)*.8)list.push('Средний доход ниже обычного оклада — проверьте ручные выходы и отсутствия.');return list.length?list:['График и выплаты синхронизированы. Можно открыть ленту и поделиться рабочей новостью.']},[month,year,state]);
 const saveTip=()=>{if(!tip.trim())return;patch({shiftNotes:{...state.shiftNotes,[iso(now)]:`${state.shiftNotes[iso(now)]||''}${state.shiftNotes[iso(now)]?'\n':''}${tip.trim()}`}});setTip('');onNotice('Совет сохранён в заметках текущего дня')};
 const backup=async()=>{if(!backupPassword){onNotice('Введите пароль для шифрования резервной копии');return}try{download(`workertink-backup-${iso(now)}.wtbackup`,await encryptBackup(state,backupPassword));setBackupPassword('');onNotice('Зашифрованная резервная копия создана')}catch{onNotice('Не удалось создать резервную копию')}};
 return <section className="redesign-page redesign-home">
  <div className="redesign-page-intro">
   <div><span className="redesign-overline">Сегодня · {now.toLocaleDateString('ru-RU')}</span><h1>Ваш день в WTinker</h1><p>Рабочий ритм, деньги и люди — без переходов между несвязанными инструментами.</p></div>
   <div className="redesign-intro-actions"><button className="redesign-btn redesign-btn-primary" onClick={()=>go('social')}>Открыть ленту</button><button className="redesign-btn" onClick={()=>go('calendar')}>График</button></div>
  </div>
  <div className="home-snapshot">
   <article className="snapshot-card snapshot-primary"><span>На руки в этом месяце</span><strong>{formatMoney(month.net)}</strong><small>{month.work} смен · {month.sickDays} дн. больничного</small></article>
   <article className="snapshot-card"><span>Годовой доход</span><strong>{formatMoney(year.net)}</strong><small>{formatMoney(year.averageMonthlyNet)} в среднем / мес.</small></article>
   <article className="snapshot-card"><span>Отпуск</span><strong>{Math.max(0,state.vacTotal-vacationUsedDays(state))}</strong><small>дней осталось</small></article>
   <article className="snapshot-card"><span>Выходные</span><strong>{daysOff(state,30)}</strong><small>в ближайшие 30 дней</small></article>
  </div>
  <div className="home-main-grid">
   <section className="redesign-panel home-schedule">
    <div className="redesign-panel-head"><div><span className="redesign-overline">Ближайшие дни</span><h2>Ваш график</h2></div><button className="redesign-link" onClick={()=>go('calendar')}>Открыть календарь <Icon name="chevronRight" size={14}/></button></div>
    <div className="schedule-strip">{Array.from({length:7},(_,i)=>{const d=addDays(now,i);const s=getScheduledShift(state,d);return <button key={i} className={i===0?'today':''} onClick={()=>go('calendar')}><span>{d.toLocaleDateString('ru-RU',{weekday:'short'})}</span><b>{d.getDate()}</b><em className={s==='off'?'off':s==='night'?'night':'work'}>{s==='off'?'Выходной':s==='night'?'Ночь':s==='full'?'Сутки':'День'}</em></button>})}</div>
   </section>
   <aside className="redesign-panel home-priority"><div className="redesign-panel-head"><div><span className="redesign-overline">Сейчас важно</span><h2>Проверьте</h2></div></div><div className="priority-list"><div><b>{month.nightWork?'Ночная доплата':'График'}</b><span>{month.nightWork?'Есть ночные смены в текущем месяце.':'График не требует изменений.'}</span></div><div><b>{month.vacDays?'Отпуск':'Доход'}</b><span>{month.vacDays?'В этом месяце есть дни отпуска.':'Расходы и выплаты можно проверить в разделе «Зарплата».'}</span></div><div><b>Люди</b><span>Откройте ленту, чтобы увидеть рабочие новости и обсуждения.</span></div></div><button className="redesign-btn redesign-btn-soft" onClick={()=>go('social')}>Перейти в сеть</button></aside>
  </div>
  <div className="home-content-grid">
   <section className="redesign-panel"><div className="redesign-panel-head"><div><span className="redesign-overline">Прогноз</span><h2>Доход на {forecastMonths} мес.</h2></div><strong className="metric-large">{formatMoney(forecast.net)}</strong></div><input className="redesign-range" type="range" min="1" max="12" value={forecastMonths} onChange={e=>setForecastMonths(Number(e.target.value))}/><div className="range-meta"><span>1 мес.</span><span>Среднее {formatMoney(forecast.avg)} / мес.</span><span>12 мес.</span></div></section>
   <section className="redesign-panel"><div className="redesign-panel-head"><div><span className="redesign-overline">Отпуск</span><h2>Спланировать заранее</h2></div><span className="panel-status">Доступно {Math.max(0,state.vacTotal-vacationUsedDays(state))} дн.</span></div><div className="inline-form"><input type="date" value={vacStart} onChange={e=>setVacStart(e.target.value)}/><input type="number" min="1" max="60" value={vacLength} onChange={e=>setVacLength(Number(e.target.value)||1)}/></div>{plannedVacation?<p className="panel-copy"><b>{plannedVacation.period.start} → {plannedVacation.period.end}</b><br/>{plannedVacation.days} оплачиваемых дней</p>:<p className="panel-copy">Выберите начало и длительность, чтобы увидеть прогноз по календарным дням.</p>}</section>
   <section className="redesign-panel"><div className="redesign-panel-head"><div><span className="redesign-overline">Сценарий</span><h2>Что изменится?</h2></div><strong className="metric-large">{formatMoney(scenario.net)}</strong></div><label className="redesign-field">Оклад<input type="number" value={scenarioSalary} onChange={e=>setScenarioSalary(Number(e.target.value)||0)}/></label><label className="redesign-field">Ночная доплата · {scenarioNight}%<input className="redesign-range" type="range" min="0" max="100" value={scenarioNight} onChange={e=>setScenarioNight(Number(e.target.value))}/></label><p className="panel-copy">Расчёт сценария не меняет ваши реальные настройки.</p></section>
   <section className="redesign-panel"><div className="redesign-panel-head"><div><span className="redesign-overline">Безопасность</span><h2>Аккаунт под контролем</h2></div></div><div className="security-summary"><div><b>OnePass</b><span>{state.onePassEnabled?'Включён':'Можно подключить'}</span></div><div><b>Данные</b><span>Хранятся локально и синхронизируются только нужные профильные поля.</span></div></div><button className="redesign-btn redesign-btn-soft" onClick={()=>go('settings')}>Открыть настройки</button></section>
  </div>
  <div className="home-content-grid home-tools-grid">
   <section className="redesign-panel"><div className="redesign-panel-head"><div><span className="redesign-overline">Больничный</span><h2>Сценарий выплаты</h2></div><strong className="metric-large">{formatMoney(sickPay)}</strong></div><input className="redesign-range" type="range" min="1" max="30" value={sickDays} onChange={e=>setSickDays(Number(e.target.value))}/><div className="range-meta"><span>1 день</span><span>{sickDays} дней · коэффициент {Math.round(sickRate*100)}%</span><span>30 дней</span></div><p className="panel-copy">Прогноз по текущему среднему заработку и стажу. Реальные данные профиля не изменяются.</p></section>
   <section className="redesign-panel"><div className="redesign-panel-head"><div><span className="redesign-overline">Статистика</span><h2>{now.getFullYear()} год</h2></div><button className="redesign-link" onClick={()=>go('pay')}>Подробнее <Icon name="chevronRight" size={14}/></button></div><div className="security-summary"><div><b>{year.work}</b><span>смен</span></div><div><b>{formatMoney(year.net)}</b><span>на руки</span></div><div><b>{year.vacDays}</b><span>дней отпуска</span></div><div><b>{year.sickDays}</b><span>дней больничного</span></div></div></section>
   <section className="redesign-panel"><div className="redesign-panel-head"><div><span className="redesign-overline">Личная заметка</span><h2>Сохранить мысль</h2></div></div><input className="panel-input" value={tip} onChange={e=>setTip(e.target.value)} placeholder={tips[0]}/><div className="inline-form inline-form-single"><button className="redesign-btn redesign-btn-soft" onClick={saveTip}>Сохранить в сегодняшний день</button></div><p className="panel-copy">{tips[0]}</p></section>
   <section className="redesign-panel"><div className="redesign-panel-head"><div><span className="redesign-overline">Резервная копия</span><h2>Зашифровать локальные данные</h2></div></div><p className="panel-copy">AES-GCM + PBKDF2. Пароль остаётся на устройстве и не передаётся на сервер.</p><div className="backup-row"><input className="panel-input" type="password" value={backupPassword} onChange={e=>setBackupPassword(e.target.value)} placeholder="Пароль резервной копии"/><button className="redesign-btn redesign-btn-primary" onClick={()=>void backup()}>Экспорт</button></div></section>
  </div>
  <div className="redesign-social-callout"><div><span className="redesign-overline">WTinker · социальная сеть для работы</span><h2>Рабочие новости должны быть рядом с людьми.</h2><p>Публикации, сообщества, сообщения и рабочие действия живут в одном контексте — так меньше переключений и потерянных договорённостей.</p></div><button className="redesign-btn redesign-btn-primary" onClick={()=>go('social')}>Открыть ленту <Icon name="chevronRight" size={14}/></button></div>
 </section>;
}
