import {useEffect,useMemo,useState} from 'react';
import type {UserProfile} from './core';
import {addSocialComment,createNetworkEvent,createNetworkGroup,createShiftSwap,createSocialPost,getNetworkGroups,getNetworkHome,getSavedNetworkPosts,joinNetworkEvent,joinNetworkGroup,leaveNetworkGroup,claimShiftSwap,saveNetworkPost,searchNetworkPeople,toggleSocialLike,getSocialComments,type DirectoryFriend,type NetworkEvent,type NetworkGroup,type NetworkPerson,type ShiftSwap,type SocialComment,type SocialPost} from './directory';

type Props={token:string;profile:UserProfile;onNotice:(text:string)=>void;onChat?:(profileId:string)=>void};
type Area='feed'|'groups'|'events'|'swaps'|'saved'|'people';
function Avatar({p,size='md'}:{p:UserProfile;size?:'sm'|'md'|'lg'}){return p.avatar?<img className={`network-avatar ${size}`} src={p.avatar} alt=""/>:<span className={`network-avatar ${size} fallback`}>{(p.name||'?').slice(0,1).toUpperCase()}</span>}
function Name({p}:{p:UserProfile}){return <span className="network-name">{p.name}{p.isDev&&<b className="dev-badge">dev</b>}</span>}
function ago(ts:number){const d=Math.max(1,Date.now()-ts);if(d<60000)return 'только что';if(d<3600000)return `${Math.floor(d/60000)} мин назад`;if(d<86400000)return `${Math.floor(d/3600000)} ч назад`;return new Date(ts).toLocaleDateString('ru-RU')}
function dateTime(ts:number){return new Date(ts).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}

export default function NetworkView({token,profile,onNotice,onChat}:Props){
 const [area,setArea]=useState<Area>('feed'); const [posts,setPosts]=useState<SocialPost[]>([]); const [saved,setSaved]=useState<SocialPost[]>([]); const [groups,setGroups]=useState<NetworkGroup[]>([]); const [events,setEvents]=useState<NetworkEvent[]>([]); const [swaps,setSwaps]=useState<ShiftSwap[]>([]); const [people,setPeople]=useState<NetworkPerson[]>([]); const [draft,setDraft]=useState(''); const [kind,setKind]=useState<'post'|'announcement'|'question'|'shift'>('post'); const [groupId,setGroupId]=useState(''); const [comments,setComments]=useState<Record<string,SocialComment[]>>({}); const [openComments,setOpenComments]=useState<Record<string,boolean>>({}); const [comment,setComment]=useState<Record<string,string>>({}); const [search,setSearch]=useState(''); const [busy,setBusy]=useState(false); const [groupForm,setGroupForm]=useState({name:'',description:'',visibility:'public' as 'public'|'private'}); const [eventForm,setEventForm]=useState({title:'',description:'',kind:'Обучение',startsAt:'',location:'',groupId:''}); const [swapForm,setSwapForm]=useState({date:'',shift:'День',requestedShift:'День',note:''});
 const refresh=async()=>{try{const [home,feed,savedRows]=await Promise.all([getNetworkHome(token),import('./directory').then(m=>m.getSocialFeed(token,60)),getSavedNetworkPosts(token)]);setGroups(home.groups);setEvents(home.events);setSwaps(home.swaps);setPeople(home.people);setPosts(feed.posts);setSaved(savedRows.posts)}catch{onNotice('Не удалось обновить рабочую сеть')}};
 useEffect(()=>{void refresh();const t=window.setInterval(()=>void refresh(),30000);return()=>window.clearInterval(t)},[token]);
 const visible=area==='saved'?saved:posts;
 const publish=async()=>{if(!draft.trim())return;setBusy(true);try{await createSocialPost(draft.trim(),token,{kind,groupId:groupId||null});setDraft('');setKind('post');setGroupId('');await refresh();onNotice('Публикация опубликована')}catch(e){onNotice(String(e).replace('Error:',''))}finally{setBusy(false)}};
 const toggleSave=async(p:SocialPost)=>{try{const next=!saved.some(x=>x.id===p.id);await saveNetworkPost(p.id,next,token);setSaved(s=>next?[p,...s.filter(x=>x.id!==p.id)]:s.filter(x=>x.id!==p.id));onNotice(next?'Сохранено в закладки':'Удалено из закладок')}catch{onNotice('Не удалось изменить закладку')}};
 const loadComments=async(id:string)=>{try{const r=await getSocialComments(id,token);setComments(c=>({...c,[id]:r.comments}));setOpenComments(c=>({...c,[id]:true}))}catch{onNotice('Не удалось загрузить комментарии')}};
 const addComment=async(id:string)=>{const body=(comment[id]||'').trim();if(!body)return;try{await addSocialComment(id,body,token);setComment(c=>({...c,[id]:''}));await loadComments(id)}catch{onNotice('Не удалось добавить комментарий')}};
 const makeGroup=async()=>{if(!groupForm.name.trim())return;try{const r=await createNetworkGroup(groupForm,token);setGroups(g=>[r.group,...g]);setGroupForm({name:'',description:'',visibility:'public'});setArea('groups');onNotice('Сообщество создано')}catch(e){onNotice(String(e).replace('Error:',''))}};
 const makeEvent=async()=>{if(!eventForm.title||!eventForm.startsAt)return;try{const r=await createNetworkEvent({title:eventForm.title,description:eventForm.description,kind:eventForm.kind,startsAt:new Date(eventForm.startsAt).getTime(),location:eventForm.location,groupId:eventForm.groupId||null},token);setEvents(e=>[r.event,...e].sort((a,b)=>a.startsAt-b.startsAt));setEventForm({title:'',description:'',kind:'Обучение',startsAt:'',location:'',groupId:''});onNotice('Событие создано')}catch(e){onNotice(String(e).replace('Error:',''))}};
 const makeSwap=async()=>{if(!swapForm.date)return;try{const r=await createShiftSwap(swapForm,token);setSwaps(s=>[r.swap,...s]);setSwapForm({date:'',shift:'День',requestedShift:'День',note:''});onNotice('Запрос на обмен сменой опубликован')}catch(e){onNotice(String(e).replace('Error:',''))}};
 const searchPeople=async()=>{try{const r=await searchNetworkPeople(search,token);setPeople(r.people);setArea('people')}catch{onNotice('Не удалось найти сотрудников')}};
 return <section className="network-page">
   <header className="network-hero"><div><span className="eyebrow">WORKERTINK NETWORK</span><h1>Рабочая сеть, а не просто календарь</h1><p>Коллеги, профессиональные сообщества, рабочие события, обмен сменами и полезные публикации — в одном пространстве.</p></div><div className="network-hero-actions"><button onClick={()=>setArea('people')}>Найти коллегу</button><button className="primary" onClick={()=>setArea('groups')}>Создать сообщество</button></div></header>
   <div className="network-nav">{([['feed','Лента'],['groups','Сообщества'],['events','События'],['swaps','Обмен сменами'],['saved','Сохранённое'],['people','Люди']] as [Area,string][]).map(([id,label])=><button key={id} className={area===id?'active':''} onClick={()=>setArea(id)}>{label}</button>)}</div>
   {area==='feed'&&<div className="network-grid"><main>
     <div className="network-compose"><div className="compose-top"><Avatar p={profile}/><div><Name p={profile}/><span>Публикация видна рабочей сети</span></div></div><div className="compose-types">{([['post','Пост'],['announcement','Объявление'],['question','Вопрос'],['shift','Смена']] as const).map(([id,label])=><button className={kind===id?'active':''} onClick={()=>setKind(id)} key={id}>{label}</button>)}</div><textarea value={draft} onChange={e=>setDraft(e.target.value.slice(0,4000))} placeholder={kind==='question'?'Задайте вопрос коллегам…':kind==='announcement'?'Сообщите важную рабочую новость…':kind==='shift'?'Расскажите о смене или потребности в обмене…':'Поделитесь рабочим опытом, находкой или новостью…'}/><div className="compose-bottom"><select value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">В общую сеть</option>{groups.filter(g=>g.joined).map(g=><option value={g.id} key={g.id}>Сообщество: {g.name}</option>)}</select><span>{draft.length}/4000</span><button className="primary" disabled={busy||!draft.trim()} onClick={()=>void publish()}>Опубликовать</button></div></div>
     <div className="network-feed">{visible.map(p=><PostCard key={p.id} post={p} saved={saved.some(x=>x.id===p.id)} comments={comments[p.id]||[]} commentsOpen={Boolean(openComments[p.id])} comment={comment[p.id]||''} onLike={async()=>{const r=await toggleSocialLike(p.id,token);setPosts(rows=>rows.map(x=>x.id===p.id?{...x,liked:r.liked,likes:r.likes}:x));setSaved(rows=>rows.map(x=>x.id===p.id?{...x,liked:r.liked,likes:r.likes}:x))}} onSave={()=>void toggleSave(p)} onComments={()=>openComments[p.id]?setOpenComments(x=>({...x,[p.id]:false})):void loadComments(p.id)} onCommentChange={v=>setComment(c=>({...c,[p.id]:v}))} onComment={()=>void addComment(p.id)} onChat={onChat}/>)}</div>
   </main><aside className="network-rail"><div className="network-widget"><div className="widget-title"><b>Ваши пространства</b><button onClick={()=>setArea('groups')}>Все</button></div>{groups.slice(0,5).map(g=><div className="group-mini" key={g.id}><span className="group-mark">{g.name.slice(0,1)}</span><div><b>{g.name}</b><small>{g.members} участников</small></div></div>)}{!groups.length&&<p>Создайте первое рабочее сообщество.</p>}</div><div className="network-widget"><div className="widget-title"><b>Ближайшее</b><button onClick={()=>setArea('events')}>Все</button></div>{events.slice(0,4).map(e=><div className="event-mini" key={e.id}><time>{dateTime(e.startsAt)}</time><b>{e.title}</b><small>{e.location||'Онлайн / без места'}</small></div>)}{!events.length&&<p>Пока нет рабочих событий.</p>}</div><div className="network-widget accent"><b>Рабочая идея</b><p>Используйте «Объявление» для важных новостей, «Вопрос» — для коллег, а «Обмен сменами» — вместо сообщений в разрозненных чатах.</p></div></aside></div>}
   {area==='groups'&&<Groups groups={groups} form={groupForm} setForm={setGroupForm} onCreate={()=>void makeGroup()} onJoin={async g=>{try{if(g.joined)await leaveNetworkGroup(g.id,token);else await joinNetworkGroup(g.id,token);setGroups(gs=>gs.map(x=>x.id===g.id?{...x,joined:!x.joined,members:Math.max(0,x.members+(x.joined?-1:1))}:x))}catch{onNotice('Не удалось изменить участие')}}}/>} 
   {area==='events'&&<Events events={events} groups={groups} form={eventForm} setForm={setEventForm} onCreate={()=>void makeEvent()} onJoin={async e=>{try{await joinNetworkEvent(e.id,'going',token);setEvents(es=>es.map(x=>x.id===e.id?{...x,joined:true,going:x.joined?x.going:x.going+1}:x))}catch{onNotice('Не удалось записаться на событие')}}}/>} 
   {area==='swaps'&&<Swaps swaps={swaps} form={swapForm} setForm={setSwapForm} onCreate={()=>void makeSwap()} onClaim={async id=>{try{await claimShiftSwap(id,token);setSwaps(s=>s.map(x=>x.id===id?{...x,status:'claimed'}:x));onNotice('Запрос принят')}catch{onNotice('Эта смена уже занята')}}}/>} 
   {area==='saved'&&<div className="network-single"><div className="page-intro"><span className="eyebrow">ЛИЧНАЯ ПОДБОРКА</span><h2>Сохранённое</h2><p>Публикации, к которым вы хотите вернуться позже.</p></div>{visible.map(p=><PostCard key={p.id} post={p} saved comments={comments[p.id]||[]} commentsOpen={Boolean(openComments[p.id])} comment={comment[p.id]||''} onLike={async()=>{const r=await toggleSocialLike(p.id,token);setSaved(rows=>rows.map(x=>x.id===p.id?{...x,liked:r.liked,likes:r.likes}:x))}} onSave={()=>void toggleSave(p)} onComments={()=>openComments[p.id]?setOpenComments(x=>({...x,[p.id]:false})):void loadComments(p.id)} onCommentChange={v=>setComment(c=>({...c,[p.id]:v}))} onComment={()=>void addComment(p.id)} onChat={onChat}/>)}{!visible.length&&<div className="network-empty">Нет сохранённых публикаций.</div>}</div>}
   {area==='people'&&<div className="network-single"><div className="people-search"><div><span className="eyebrow">КАТАЛОГ</span><h2>Люди WorkerTink</h2></div><div><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void searchPeople()} placeholder="Имя, должность или WTinkID"/><button className="primary" onClick={()=>void searchPeople()}>Найти</button></div></div><div className="people-grid">{people.map(p=><div className="person-card" key={p.profile.profileId}><Avatar p={p.profile} size="lg"/><div><Name p={p.profile}/><span>{p.profile.position||'Сотрудник'}</span><small><i className={p.online?'online':'offline'}/>{p.online?'В сети':'Не в сети'}{p.mutualFriends?` · ${p.mutualFriends} общих`:''}</small></div><div className="person-actions">{p.connected?<button onClick={()=>onChat?.(p.profile.profileId)}>Написать</button>:<button onClick={()=>onNotice('Отправьте заявку через профиль коллеги')}>Открыть профиль</button>}</div></div>)}</div></div>}
 </section>
}

function PostCard({post,saved,comments,commentsOpen,comment,onLike,onSave,onComments,onCommentChange,onComment,onChat}:{post:SocialPost;saved:boolean;comments:SocialComment[];commentsOpen:boolean;comment:string;onLike:()=>void;onSave:()=>void;onComments:()=>void;onCommentChange:(v:string)=>void;onComment:()=>void;onChat?:(id:string)=>void}){return <article className={`network-post kind-${post.kind||'post'}`}><header><Avatar p={post.author}/><div><Name p={post.author}/><span>{post.author.position||'Сотрудник'} · {ago(post.createdAt)}</span></div><b className="post-kind">{post.kind==='question'?'Вопрос':post.kind==='announcement'?'Объявление':post.kind==='shift'?'Смена':'Пост'}</b></header><p className="post-text">{post.body}</p><footer><button className={post.liked?'liked':''} onClick={onLike}>♥ {post.likes}</button><button onClick={onComments}>💬 {post.comments}</button><button className={saved?'saved':''} onClick={onSave}>{saved?'★ Сохранено':'☆ Сохранить'}</button><button onClick={()=>onChat?.(post.author.profileId)}>Написать автору</button></footer>{commentsOpen&&<div className="post-comments">{comments.map(c=><div className="comment-row" key={c.id}><Avatar p={c.author} size="sm"/><div><b>{c.author.name}</b><p>{c.body}</p><small>{ago(c.createdAt)}</small></div></div>)}<div className="comment-input"><input value={comment} onChange={e=>onCommentChange(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void onComment()} placeholder="Ваш комментарий…"/><button onClick={onComment}>➤</button></div></div>}</article>}

function Groups({groups,form,setForm,onCreate,onJoin}:{groups:NetworkGroup[];form:{name:string;description:string;visibility:'public'|'private'};setForm:(v:{name:string;description:string;visibility:'public'|'private'})=>void;onCreate:()=>void;onJoin:(g:NetworkGroup)=>void}){return <div className="network-single"><div className="page-intro"><span className="eyebrow">COMMUNITIES</span><h2>Профессиональные сообщества</h2><p>Отделы, профессии, бригады и вахты могут иметь собственное пространство для общения и рабочих публикаций.</p></div><div className="create-panel"><input placeholder="Название сообщества" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="О чём сообщество" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value as 'public'|'private'})}><option value="public">Открытое</option><option value="private">Закрытое</option></select><button className="primary" onClick={onCreate}>Создать</button></div><div className="group-grid">{groups.map(g=><article className="group-card" key={g.id}><div className="group-cover"><span>{g.name.slice(0,1).toUpperCase()}</span></div><span className="eyebrow">{g.visibility==='private'?'ЗАКРЫТОЕ':'ОТКРЫТОЕ'}</span><h3>{g.name}</h3><p>{g.description||'Рабочее пространство WorkerTink'}</p><small>{g.members} участников · владелец {g.owner.name}</small><button className={g.joined?'':'primary'} onClick={()=>onJoin(g)}>{g.joined?'Выйти из сообщества':'Вступить'}</button></article>)}</div></div>}

function Events({events,groups,form,setForm,onCreate,onJoin}:{events:NetworkEvent[];groups:NetworkGroup[];form:{title:string;description:string;kind:string;startsAt:string;location:string;groupId:string};setForm:(v:any)=>void;onCreate:()=>void;onJoin:(e:NetworkEvent)=>void}){return <div className="network-single"><div className="page-intro"><span className="eyebrow">WORK EVENTS</span><h2>Рабочие события</h2><p>Обучение, собрания, встречи команды и другие события, которые не должны теряться в личных чатах.</p></div><div className="create-panel event-form"><input placeholder="Название события" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Описание" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/><input placeholder="Место или ссылка" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><select value={form.groupId} onChange={e=>setForm({...form,groupId:e.target.value})}><option value="">Без сообщества</option>{groups.filter(g=>g.joined).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button className="primary" onClick={onCreate}>Создать событие</button></div><div className="event-list">{events.map(e=><article className="event-card" key={e.id}><div className="event-date"><b>{new Date(e.startsAt).getDate()}</b><span>{new Date(e.startsAt).toLocaleDateString('ru-RU',{month:'short'})}</span></div><div><span className="eyebrow">{e.kind}</span><h3>{e.title}</h3><p>{e.description||'Без описания'}</p><small>{dateTime(e.startsAt)} · {e.location||'Онлайн'} · {e.going} участников</small></div><button className={e.joined?'':'primary'} onClick={()=>onJoin(e)}>{e.joined?'Вы записаны':'Участвовать'}</button></article>)}</div></div>}

function Swaps({swaps,form,setForm,onCreate,onClaim}:{swaps:ShiftSwap[];form:{date:string;shift:string;requestedShift:string;note:string};setForm:(v:any)=>void;onCreate:()=>void;onClaim:(id:string)=>void}){return <div className="network-single"><div className="page-intro"><span className="eyebrow">SHIFT EXCHANGE</span><h2>Обмен сменами</h2><p>Публикуйте потребность в обмене сменой — коллеги смогут принять запрос без ручной переписки.</p></div><div className="create-panel"><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><select value={form.shift} onChange={e=>setForm({...form,shift:e.target.value})}><option>День</option><option>Ночь</option><option>Сутки</option></select><span className="swap-arrow">→</span><select value={form.requestedShift} onChange={e=>setForm({...form,requestedShift:e.target.value})}><option>День</option><option>Ночь</option><option>Сутки</option></select><input placeholder="Комментарий" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><button className="primary" onClick={onCreate}>Опубликовать</button></div><div className="swap-list">{swaps.map(s=><article className="swap-card" key={s.id}><Avatar p={s.owner}/><div><b>{s.owner.name}</b><span>{s.date} · {s.shift} <strong>→</strong> {s.requestedShift}</span><small>{s.note||'Без комментария'}</small></div><button className="primary" disabled={s.status!=='open'} onClick={()=>onClaim(s.id)}>{s.status==='open'?'Принять обмен':'Занято'}</button></article>)}</div></div>}
