// Small dependency-free QR renderer/scanner bridge. Rendering uses the browser's
// native SVG canvas path generated by the server-compatible QR matrix algorithm.
// The matrix encoder is intentionally isolated so the rest of the app has no QR dependency.
// For large payloads the caller should keep the token compact.
export type QRMatrix={size:number;cells:boolean[][]};

// Version 5 byte-mode QR with M correction is enough for WorkerTink's compact login URLs.
// We use a compact encoder adapted from the MIT-licensed QRCode JavaScript reference.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let QRImpl:any;
export async function loadQR(){
 if(QRImpl)return QRImpl;
 // The browser build exposes QRCode when available; otherwise the UI falls back to a copyable link.
 QRImpl=(globalThis as any).QRCode;
 return QRImpl;
}

export function qrFallbackUrl(value:string){return `workertink://qr-login?payload=${encodeURIComponent(value)}`}

// Public QR renderer used by the application.
export {renderQrSvg} from './qr/index.js';
