import {useEffect,useMemo,useState} from 'react';
import type {UserProfile} from './core';
import {addSocialComment,createSocialPost,deleteSocialPost,getSocialComments,getSocialFeed,getSocialMessages,getSocialNotifications,getDirectoryFriends,readAllSocialNotifications,readSocialNotification,sendSocialMessage,toggleSocialLike,type DirectoryFriend,type SocialComment,type SocialMessage,type SocialNotification,type SocialPost} from './directory';

type Props={token:string;profile:UserProfile;onNotice:(text:string)=>void;initialPostId?:string};
type Section='feed'|'messages'|'notifications'|'people';
const DEV_WTINK_ID='WTinkID-214994';
const dev=(p:UserProfile)=>p.profileId.trim().toUpperCase()===DEV_WTINK_ID.toUpperCase();
function Name({p}:{p:UserProfile}){return <span className="social-name">{p.name}{dev(p)&&<b className="dev-badge">dev</b>}</span>}
function Avatar({p}:{p:UserProfile}){return p.avatar?<img className="social-avatar" src={p.avatar} alt=""/>:<span className="social-avatar social-avatar-fallback">{(p.name||'?').slice(0,1).toUpperCase()}</span>}
function ago(ts:number){const s=Math.max(1,Math.floor((Date.now()-ts)/1000));if(s<60)return `${s} с`;if(s<3600)return `${Math.floor(s/60)} мин`;if(s<86400)return `${Math.floor(s/3600)} ч`;return new Date(ts).toLocaleDateString('ru-RU')}

export default function SocialView({token,profile,onNotice,initialPostId}:Props){
 const [section,setSection]=useState<Section>('feed'); const [posts,setPosts]=useState<SocialPost[]>([]); const [notifications,setNotifications]=useState<SocialNotification[]>([]); const [unread,setUnread]=useState(0); const [friends,setFriends]=useState<DirectoryFriend[]>([]); const [activeFriend,setActiveFriend]=useState<UserProfile|null>(null); const [messages,setMessages]=useState<SocialMessage[]>([]); const [busy,setBusy]=useState(false); const [draft,setDraft]=useState(''); const [commentDraft,setCommentDraft]=useState<Record<string,string>>({}); const [comments,setComments]=useState<Record<string,SocialComment[]>>({}); const [expanded,setExpanded]=useState<Record<string,boolean>>({}); const [postId,setPostId]=useState(initialPostId||'');
 const refresh=async()=>{try{const [feed,note,people]=await Promise.all([getSocialFeed(token,30),getSocialNotifications(token),getDirectoryFriends(token)]);setPosts(feed.posts);setNotifications(note.notifications);setUnread(note.unread);setFriends(people.friends);if(initialPostId&&!feed.posts.some(p=>p.id===initialPostId))setPostId('')}catch{onNotice('Не удалось обновить социальную ленту')}};
 useEffect(()=>{void refresh();const t=window.setInterval(()=>void refresh(),15000);return()=>window.clearInterval(t)},[token]);
 useEffect(()=>{if(!activeFriend)return;let cancelled=false;const load=async()=>{try{const r=await getSocialMessages(activeFriend.profileId,token);if(!cancelled)setMessages(r.messages)}catch{if(!cancelled)onNotice('Не удалось загрузить сообщения')}};void load();const t=window.setInterval(load,4000);return()=>{cancelled=true;window.clearInterval(t)}},[activeFriend,token]);
 const visiblePosts=useMemo(()=>postId?posts.filter(p=>p.id===postId):posts,[posts,postId]);
 const publish=async()=>{if(!draft.trim())return;setBusy(true);try{await createSocialPost(draft.trim(),token);setDraft('');await refresh();onNotice('Публикация размещена')}catch(e){onNotice(String(e).replace('Error:',''))}finally{setBusy(false)}};
 const like=async(id:string)=>{try{const r=await toggleSocialLike(id,token);setPosts(p=>p.map(x=>x.id===id?{...x,liked:r.liked,likes:r.likes}:x))}catch{onNotice('Не удалось поставить реакцию')}};
 const loadComments=async(id:string)=>{try{const r=await getSocialComments(id,token);setComments(c=>({...c,[id]:r.comments}));setExpanded(x=>({...x,[id]:true}))}catch{onNotice('Не удалось загрузить комментарии')}};
 const comment=async(id:string)=>{const body=(commentDraft[id]||'').trim();if(!body)return;try{await addSocialComment(id,body,token);setCommentDraft(c=>({...c,[id]:''}));await loadComments(id)}catch{onNotice('Не удалось добавить комментарий')}};
 const message=async()=>{if(!activeFriend||!draft.trim())return;try{const r=await sendSocialMessage(activeFriend.profileId,draft.trim(),token);setMessages(m=>[...m,r.message]);setDraft('')}catch{onNotice('Не удалось отправить сообщение')}};
 return <section className="social-page">
  <div className="social-hero"><div><span className="eyebrow">WorkerTink Community</span><h2>Рабочая социальная сеть</h2><p>Общайтесь с коллегами, делитесь рабочими новостями и оставайтесь на связи.</p></div><div className="social-hero-stats"><span><b>{friends.length}</b> контактов</span><span><b>{unread}</b> новых</span></div></div>
  <div className="social-tabs"><button className={section==='feed'?'active':''} onClick={()=>{setSection('feed');setPostId('')}}>Лента</button><button className={section==='messages'?'active':''} onClick={()=>setSection('messages')}>Сообщения</button><button className={section==='notifications'?'active':''} onClick={()=>setSection('notifications')}>Уведомления {unread>0&&<b>{unread}</b>}</button><button className={section==='people'?'active':''} onClick={()=>setSection('people')}>Люди</button></div>
  {section==='feed'&&<div className="social-layout"><div className="social-main"><div className="social-compose"><div className="social-compose-head"><Avatar p={profile}/><div><Name p={profile}/><small>Что происходит на работе?</small></div></div><textarea value={draft} onChange={e=>setDraft(e.target.value.slice(0,4000))} placeholder="Поделитесь новостью, опытом или полезным советом…"/><div className="social-compose-foot"><span>{draft.length}/4000</span><button className="btn primary" disabled={busy||!draft.trim()} onClick={()=>void publish()}>Опубликовать</button></div></div>
   {visiblePosts.map(post=><article className={`social-post ${post.id===postId?'focus':''}`} key={post.id}><header><Avatar p={post.author}/><div><Name p={post.author}/><small>{post.author.position||'Сотрудник'} · {ago(post.createdAt)}</small></div>{(post.author.profileId===profile.profileId||profile.isAdmin||dev(profile))&&<button className="social-more" onClick={async()=>{if(confirm('Удалить публикацию?')){try{await deleteSocialPost(post.id,token);setPosts(p=>p.filter(x=>x.id!==post.id))}catch{onNotice('Не удалось удалить публикацию')}}}}>×</button>}</header><p className="social-post-body">{post.body}</p><div className="social-actions"><button className={post.liked?'liked':''} onClick={()=>void like(post.id)}>♥ {post.likes}</button><button onClick={()=>expanded[post.id]?setExpanded(x=>({...x,[post.id]:false})):void loadComments(post.id)}>💬 {post.comments}</button><button onClick={()=>{navigator.clipboard?.writeText(`${location.origin}${location.pathname}?tab=social&post=${post.id}`);onNotice('Ссылка на публикацию скопирована')}}>↗ Поделиться</button></div>{expanded[post.id]&&<div className="social-comments">{(comments[post.id]||[]).map(c=><div className="social-comment" key={c.id}><Avatar p={c.author}/><div><Name p={c.author}/><p>{c.body}</p><small>{ago(c.createdAt)}</small></div></div>)}<div className="social-comment-compose"><input value={commentDraft[post.id]||''} onChange={e=>setCommentDraft(x=>({...x,[post.id]:e.target.value.slice(0,1000)}))} placeholder="Написать комментарий…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void comment(post.id)}}}/><button onClick={()=>void comment(post.id)}>➤</button></div></div>}</article>)}{!visiblePosts.length&&<div className="social-empty"><b>Лента пока пуста</b><span>Опубликуйте первую рабочую новость.</span></div>}</div><aside className="social-side"><div className="social-card"><h3>На связи</h3>{friends.slice(0,8).map(f=><button className="social-person" key={f.profile.profileId} onClick={()=>{setActiveFriend(f.profile);setSection('messages')}}><Avatar p={f.profile}/><span><Name p={f.profile}/><small><i className={f.online?'online-dot':'offline-dot'}/>{f.online?'В сети':'Не в сети'}</small></span></button>)}{!friends.length&&<p className="hint">Добавьте коллег в друзья, чтобы общаться.</p>}</div><div className="social-card"><h3>Правила сообщества</h3><p>Публикуйте рабочий опыт и полезную информацию. Не размещайте пароли, финансовые реквизиты и другую чувствительную информацию.</p></div></aside></div>}
  {section==='messages'&&<div className="social-messages"><aside className="social-chat-list">{friends.map(f=><button className={activeFriend?.profileId===f.profile.profileId?'active':''} key={f.profile.profileId} onClick={()=>setActiveFriend(f.profile)}><Avatar p={f.profile}/><span><Name p={f.profile}/><small><i className={f.online?'online-dot':'offline-dot'}/>{f.online?'В сети':'Не в сети'}</small></span></button>)}{!friends.length&&<div className="social-empty"><b>Нет контактов</b><span>Сначала добавьте коллег в друзья.</span></div>}</aside><div className="social-chat"><header>{activeFriend?<><Avatar p={activeFriend}/><div><Name p={activeFriend}/><small>{activeFriend.position||'Сотрудник'}</small></div></>:<span>Выберите коллегу</span>}</header><div className="social-chat-body">{activeFriend&&messages.map(m=><div className={`bubble ${m.from===profile.profileId?'mine':''}`} key={m.id}><p>{m.body}</p><small>{new Date(m.createdAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div>)}</div>{activeFriend&&<div className="social-chat-compose"><input value={draft} onChange={e=>setDraft(e.target.value.slice(0,4000))} placeholder="Сообщение…" onKeyDown={e=>{if(e.key==='Enter')void message()}}/><button className="btn primary" onClick={()=>void message()}>Отправить</button></div>}</div></div>}
  {section==='notifications'&&<div className="social-notifications"><div className="social-notifications-head"><div><span className="eyebrow">Центр событий</span><h3>Уведомления</h3></div><button className="btn quiet" onClick={()=>void readAllSocialNotifications(token).then(()=>{setNotifications(n=>n.map(x=>({...x,readAt:Date.now()})));setUnread(0)})}>Отметить всё прочитанным</button></div>{notifications.map(n=><button className={`social-notification ${n.readAt?'read':''}`} key={n.id} onClick={()=>void readSocialNotification(n.id,token).then(()=>{setNotifications(a=>a.map(x=>x.id===n.id?{...x,readAt:Date.now()}:x));setUnread(Math.max(0,unread-(n.readAt?0:1)));if(n.kind==='message'){setSection('messages');if(n.actor)setActiveFriend(n.actor)}else if(n.kind==='peerRequest')location.href=n.url})}><span className="social-notification-icon">{n.kind==='like'?'♥':n.kind==='comment'?'💬':n.kind==='message'?'✉':'●'}</span><span><b>{n.title}</b><small>{n.body}</small><time>{ago(n.createdAt)}</time></span>{n.actor&&<Avatar p={n.actor}/>}</button>)}{!notifications.length&&<div className="social-empty"><b>Уведомлений пока нет</b><span>Здесь будут заявки, реакции, сообщения и P2P-запросы.</span></div>}</div>}
  {section==='people'&&<div className="social-people"><div className="social-card"><h3>Ваши контакты</h3>{friends.map(f=><div className="social-person-row" key={f.profile.profileId}><Avatar p={f.profile}/><div><Name p={f.profile}/><small>{f.profile.position||'Сотрудник'} · {f.online?'в сети':'не в сети'}</small></div><button className="btn quiet" onClick={()=>{setActiveFriend(f.profile);setSection('messages')}}>Написать</button></div>)}{!friends.length&&<div className="social-empty"><b>Контактов пока нет</b><span>Используйте раздел «Друзья», чтобы найти коллег.</span></div>}</div></div>}
 </section>
}
