import {useEffect,useMemo,useState} from 'react';
import type {UserProfile} from './core';
import {addSocialComment,createSocialPost,deleteSocialPost,getSocialComments,getSocialFeed,getSocialNotifications,getDirectoryFriends,readAllSocialNotifications,readSocialNotification,toggleSocialLike,type DirectoryFriend,type SocialComment,type SocialNotification,type SocialPost} from './directory';

type Props={token:string;profile:UserProfile;onNotice:(text:string)=>void;initialPostId?:string};
type Section='feed'|'notifications'|'people';
const DEV_WTINK_ID='WTinkID-214994';
const dev=(p:UserProfile)=>p.profileId.trim().toUpperCase()===DEV_WTINK_ID.toUpperCase();
function Name({p}:{p:UserProfile}){return <span className="social-name">{p.name}{dev(p)&&<b className="dev-badge">dev</b>}</span>}
function Avatar({p}:{p:UserProfile}){return p.avatar?<img className="social-avatar" src={p.avatar} alt=""/>:<span className="social-avatar social-avatar-fallback">{(p.name||'?').slice(0,1).toUpperCase()}</span>}
function ago(ts:number){const s=Math.max(1,Math.floor((Date.now()-ts)/1000));if(s<60)return `${s} с`;if(s<3600)return `${Math.floor(s/60)} мин`;if(s<86400)return `${Math.floor(s/3600)} ч`;return new Date(ts).toLocaleDateString('ru-RU')}

export default function SocialView({token,profile,onNotice,initialPostId}:Props){
 const [section,setSection]=useState<Section>('feed');const [posts,setPosts]=useState<SocialPost[]>([]);const [notifications,setNotifications]=useState<SocialNotification[]>([]);const [unread,setUnread]=useState(0);const [friends,setFriends]=useState<DirectoryFriend[]>([]);const [draft,setDraft]=useState('');const [commentDraft,setCommentDraft]=useState<Record<string,string>>({});const [comments,setComments]=useState<Record<string,SocialComment[]>>({});const [expanded,setExpanded]=useState<Record<string,boolean>>({});const [postId,setPostId]=useState(initialPostId||'');const [busy,setBusy]=useState(false);
 const refresh=async()=>{try{const [feed,note,people]=await Promise.all([getSocialFeed(token,30),getSocialNotifications(token),getDirectoryFriends(token)]);setPosts(feed.posts);setNotifications(note.notifications);setUnread(note.unread);setFriends(people.friends);if(initialPostId&&!feed.posts.some(p=>p.id===initialPostId))setPostId('')}catch{onNotice('Не удалось обновить социальную ленту')}};
 useEffect(()=>{void refresh();const t=window.setInterval(()=>void refresh(),15000);return()=>window.clearInterval(t)},[token]);
 const visiblePosts=useMemo(()=>postId?posts.filter(p=>p.id===postId):posts,[posts,postId]);
 const publish=async()=>{if(!draft.trim())return;setBusy(true);try{await createSocialPost(draft.trim(),token);setDraft('');await refresh();onNotice('Публикация размещена')}catch(e){onNotice(String(e).replace('Error:',''))}finally{setBusy(false)}};
 const like=async(id:string)=>{try{const r=await toggleSocialLike(id,token);setPosts(p=>p.map(x=>x.id===id?{...x,liked:r.liked,likes:r.likes}:x))}catch{onNotice('Не удалось поставить реакцию')}};
 const loadComments=async(id:string)=>{try{const r=await getSocialComments(id,token);setComments(c=>({...c,[id]:r.comments}));setExpanded(x=>({...x,[id]:true}))}catch{onNotice('Не удалось загрузить комментарии')}};
 const comment=async(id:string)=>{const body=(commentDraft[id]||'').trim();if(!body)return;try{await addSocialComment(id,body,token);setCommentDraft(c=>({...c,[id]:''}));await loadComments(id)}catch{onNotice('Не удалось добавить комментарий')}};
 return <section className="social-page">
  <div className="social-hero"><div><span className="eyebrow">WorkerTink Community</span><h2>Рабочая социальная сеть</h2><p>Публикации, уведомления и поиск коллег. Личные сообщения находятся в разделе «Чаты».</p></div><div className="social-hero-stats"><span><b>{friends.length}</b> контактов</span><span><b>{unread}</b> новых</span></div></div>
  <div className="social-tabs"><button className={section==='feed'?'active':''} onClick={()=>{setSection('feed');setPostId('')}}>Лента</button><button className={section==='notifications'?'active':''} onClick={()=>setSection('notifications')}>Уведомления {unread>0&&<b>{unread}</b>}</button><button className={section==='people'?'active':''} onClick={()=>setSection('people')}>Люди</button></div>
  {section==='feed'&&<div className="social-layout"><div className="social-main"><div className="social-compose"><div className="social-compose-head"><Avatar p={profile}/><div><Name p={profile}/><small>Что происходит на работе?</small></div></div><textarea value={draft} onChange={e=>setDraft(e.target.value.slice(0,4000))} placeholder="Поделитесь новостью, опытом или полезным советом…"/><div className="social-compose-foot"><span>{draft.length}/4000</span><button className="btn primary" disabled={busy||!draft.trim()} onClick={()=>void publish()}>Опубликовать</button></div></div>
   {visiblePosts.map(post=><article className={`social-post ${post.id===postId?'focus':''}`} key={post.id}><header><Avatar p={post.author}/><div><Name p={post.author}/><small>{post.author.position||'Сотрудник'} · {ago(post.createdAt)}</small></div>{(post.author.profileId===profile.profileId||profile.isAdmin||dev(profile))&&<button className="social-more" onClick={async()=>{if(confirm('Удалить публикацию?')){try{await deleteSocialPost(post.id,token);setPosts(p=>p.filter(x=>x.id!==post.id))}catch{onNotice('Не удалось удалить публикацию')}}}}>×</button>}</header><p className="social-post-body">{post.body}</p><div className="social-actions"><button className={post.liked?'liked':''} onClick={()=>void like(post.id)}>♥ {post.likes}</button><button onClick={()=>expanded[post.id]?setExpanded(x=>({...x,[post.id]:false})):void loadComments(post.id)}>💬 {post.comments}</button><button onClick={()=>{navigator.clipboard?.writeText(`${location.origin}${location.pathname}?tab=social&post=${post.id}`);onNotice('Ссылка на публикацию скопирована')}}>↗ Поделиться</button></div>{expanded[post.id]&&<div className="social-comments">{(comments[post.id]||[]).map(c=><div className="social-comment" key={c.id}><Avatar p={c.author}/><div><Name p={c.author}/><p>{c.body}</p><small>{ago(c.createdAt)}</small></div></div>)}<div className="social-comment-compose"><input value={commentDraft[post.id]||''} onChange={e=>setCommentDraft(x=>({...x,[post.id]:e.target.value.slice(0,1000)}))} placeholder="Написать комментарий…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void comment(post.id)}}}/><button onClick={()=>void comment(post.id)}>➤</button></div></div>}</article>)}{!visiblePosts.length&&<div className="social-empty"><b>Лента пока пуста</b><span>Опубликуйте первую рабочую новость.</span></div>}</div><aside className="social-side"><div className="social-card"><h3>На связи</h3>{friends.slice(0,8).map(f=><div className="social-person-row" key={f.profile.profileId}><Avatar p={f.profile}/><div><Name p={f.profile}/><small><i className={f.online?'online-dot':'offline-dot'}/>{f.online?'В сети':'Не в сети'}</small></div></div>)}{!friends.length&&<p className="hint">Добавьте коллег в друзья, чтобы общаться.</p>}</div><div className="social-card"><h3>Правила сообщества</h3><p>Публикуйте рабочий опыт и полезную информацию. Не размещайте пароли, финансовые реквизиты и другую чувствительную информацию.</p></div></aside></div>}
  {section==='notifications'&&<div className="social-notifications"><div className="social-notifications-head"><div><span className="eyebrow">Центр событий</span><h3>Уведомления</h3></div><button className="btn quiet" onClick={()=>void readAllSocialNotifications(token).then(()=>{setNotifications(n=>n.map(x=>({...x,readAt:Date.now()})));setUnread(0)})}>Отметить всё прочитанным</button></div>{notifications.map(n=><button key={n.id} className={`social-notification ${n.readAt?'read':''}`} onClick={()=>void readSocialNotification(n.id,token).then(()=>{setNotifications(items=>items.map(x=>x.id===n.id?{...x,readAt:Date.now()}:x));if(!n.readAt)setUnread(x=>Math.max(0,x-1));})}><span className="social-notification-icon">{n.kind==='message'?'✉':n.kind==='friend_request'?'👥':'•'}</span>{n.actor?<Avatar p={n.actor}/>:null}<span><b>{n.title}</b><small>{n.body}</small></span><time>{ago(n.createdAt)}</time></button>)}</div>}
  {section==='people'&&<div className="social-card social-people"><h3>Люди</h3>{friends.map(f=><div className="social-person-row" key={f.profile.profileId}><Avatar p={f.profile}/><div><Name p={f.profile}/><small>{f.profile.position||'Сотрудник'} · {f.online?'В сети':'Не в сети'}</small></div><span>{f.online?'●':'○'}</span></div>)}{!friends.length&&<div className="social-empty"><b>Нет контактов</b><span>Добавьте коллег через раздел «Друзья».</span></div>}</div>}
 </section>;
}
