import {useEffect,useState} from 'react';
import {addWorkTeamMember,createWorkDocument,createWorkTeam,deleteWorkDocument,getWorkDocuments,getWorkTeams,searchNetworkPeople,type WorkDocument,type WorkTeam} from './directory';

type Props={token:string;onNotice:(s:string)=>void};
export default function WorkTeamsView({token,onNotice}:Props){
 const [teams,setTeams]=useState<WorkTeam[]>([]);const [selected,setSelected]=useState<string>('');const [docs,setDocs]=useState<WorkDocument[]>([]);const [teamName,setTeamName]=useState('');const [teamDesc,setTeamDesc]=useState('');const [doc,setDoc]=useState({title:'',description:'',url:''});const [member,setMember]=useState('');const [busy,setBusy]=useState(false);
 const load=async()=>{try{const r=await getWorkTeams(token);setTeams(r.teams);if(!selected&&r.teams[0])setSelected(r.teams[0].id)}catch{onNotice('Не удалось загрузить рабочие команды')}};
 useEffect(()=>{void load()},[token]);
 useEffect(()=>{if(!selected){setDocs([]);return}void getWorkDocuments(selected,token).then(r=>setDocs(r.documents)).catch(()=>onNotice('Не удалось загрузить документы команды'))},[selected]);
 const create=async()=>{if(!teamName.trim())return;setBusy(true);try{const r=await createWorkTeam({name:teamName,description:teamDesc},token);setTeams(x=>[r.team,...x]);setSelected(r.team.id);setTeamName('');setTeamDesc('');onNotice('Команда создана')}catch{onNotice('Не удалось создать команду')}finally{setBusy(false)}};
 const addMember=async()=>{if(!selected||!member.trim())return;setBusy(true);try{const r=await searchNetworkPeople(member.trim(),token);const person=r.people[0];if(!person)throw new Error('NOT_FOUND');await addWorkTeamMember(selected,person.profile.profileId,token);setMember('');onNotice(`@${person.profile.username||person.profile.profileId} добавлен в команду`)}catch{onNotice('Не удалось добавить сотрудника. Проверьте username/WTinkID и права владельца.')}finally{setBusy(false)}};
 const addDoc=async()=>{if(!selected||!doc.title.trim()||!/^https?:\/\//i.test(doc.url))return;setBusy(true);try{const r=await createWorkDocument(selected,doc,token);setDocs(x=>[r.document,...x]);setDoc({title:'',description:'',url:''});onNotice('Документ добавлен')}catch{onNotice('Не удалось добавить документ')}finally{setBusy(false)}};
 const removeDoc=async(id:string)=>{try{await deleteWorkDocument(id,token);setDocs(x=>x.filter(d=>d.id!==id))}catch{onNotice('Не удалось удалить документ')}};
 return <div className="work-teams"><div className="work-teams-head"><div><span className="eyebrow">TEAMS & FILES</span><h3>Команды и рабочие документы</h3><p>Отделы, бригады и проекты с общим пространством для сотрудников и ссылок на рабочие материалы.</p></div></div><div className="teams-layout"><aside className="teams-list"><div className="team-create"><input value={teamName} onChange={e=>setTeamName(e.target.value)} placeholder="Название команды"/><input value={teamDesc} onChange={e=>setTeamDesc(e.target.value)} placeholder="Описание"/><button className="primary" disabled={busy} onClick={()=>void create()}>Создать команду</button></div>{teams.map(t=><button className={selected===t.id?'selected':''} key={t.id} onClick={()=>setSelected(t.id)}><b>{t.name}</b><span>{t.members} участников · {t.role==='owner'?'владелец':'участник'}</span></button>)}{!teams.length&&<small>Создайте первую команду.</small>}</aside><section className="team-workspace">{selected?<><div className="team-toolbar"><div><b>{teams.find(t=>t.id===selected)?.name}</b><small>{teams.find(t=>t.id===selected)?.description||'Рабочее пространство'}</small></div><div className="team-member-add"><input value={member} onChange={e=>setMember(e.target.value)} placeholder="username или WTinkID"/><button onClick={()=>void addMember()} disabled={busy}>Добавить</button></div></div><div className="document-create"><input value={doc.title} onChange={e=>setDoc({...doc,title:e.target.value})} placeholder="Название документа / ссылки"/><input value={doc.url} onChange={e=>setDoc({...doc,url:e.target.value})} placeholder="https://..."/><input value={doc.description} onChange={e=>setDoc({...doc,description:e.target.value})} placeholder="Короткое описание"/><button className="primary" onClick={()=>void addDoc()} disabled={busy}>Добавить</button></div><div className="documents-grid">{docs.map(d=><article className="document-card" key={d.id}><div className="document-icon">↗</div><div><a href={d.url} target="_blank" rel="noreferrer">{d.title}</a><p>{d.description||'Рабочий материал команды'}</p><small>{d.owner.name} · {new Date(d.updatedAt).toLocaleDateString('ru-RU')}</small></div><button onClick={()=>void removeDoc(d.id)}>×</button></article>)}{!docs.length&&<div className="work-empty">В этой команде пока нет рабочих документов. Добавьте ссылку на инструкцию, таблицу, регламент или другой материал.</div>}</div></>:<div className="work-empty">Выберите или создайте команду.</div>}</section></div></div>}
